### ISSUE TITLE
Problem with redis...

### ISSUE THREAD

**Issue by shyunsek** [chafla/Pory2#3]
I was having a look at the bot to use the cogs alongside my own, and when I tired to run the scripts, I get this error

Traceback (most recent call last):
  File "C:\Users\Deaun\Documents\MEGAsync Downloads\pikahaven\Pory2-master\main_3.py", line 202, in <module>
    bot.config = RedisConfig()
  File "C:\Users\Deaun\Documents\MEGAsync Downloads\pikahaven\Pory2-master\cogs\utils\redis_config.py", line 19, in __init__
    raise e
  File "C:\Users\Deaun\Documents\MEGAsync Downloads\pikahaven\Pory2-master\cogs\utils\redis_config.py", line 15, in __init__
    with open(config_fp, "r", encoding="utf-8") as config_raw:
FileNotFoundError: [Errno 2] No such file or directory: 'redis_config.json'
Exception ignored in: <function Redis.__del__ at 0x03B2BD68>
Traceback (most recent call last):
  File "C:\Users\Deaun\AppData\Local\Programs\Python\Python37-32\lib\site-packages\redis\client.py", line 823, in __del__
    self.close()
  File "C:\Users\Deaun\AppData\Local\Programs\Python\Python37-32\lib\site-packages\redis\client.py", line 826, in close
    conn = self.connection
AttributeError: 'RedisConfig' object has no attribute 'connection'

**Comment by chafla** [comment]
The issue you're facing is that you're not running a Redis server.
I guess I forgot to mention in the README that the bot's code is pretty heavily reliant on a Redis server running on the same machine (or externally, if you want to manually specify that) as a database. 
I don't know what you use for a database on your bot, but if you want to just grab the cogs as-is, you'll probably need to [install Redis](https://redislabs.com/ebook/appendix-a/a-3-installing-on-windows/a-3-2-installing-redis-on-window/) and configure the server and the main file to work with it. You'd also need to add a file, `redis_config.json`, to the running path which looks like:
```js
{
    "host": "localhost",
    "port": 6379,
    "db": 0,
    "decode_responses": true
}
```
If you just want something that works quickly, I'd recommend doing this. 

---

If you want something drop-in, there's a json-based Config implementation in [src/cogs/utils/config.py](https://github.com/chafla/Pory2/blob/master/cogs/utils/config.py). Redis is basically a giant key/value database anyway, so while it won't be pretty, you can likely just replace all configuration references/method calls with what exists in that object.

**Comment by chafla** [comment]
I'm also going to leave a quick note for myself here that I should have some example configuration json files in this repository, since their contents probably aren't that obvious at first glance.

**Comment by shyunsek** [comment]
I installed the redis, and its running correctly, but im getting an "auth.json not found in running directory"

**Comment by chafla** [comment]
I've added a set of template json files to the repository. Take those, add them to the running directory, and fill the discord token section with your bot's token.

**Comment by shyunsek** [comment]
thanks
